### ISSUE TITLE
id.(navbotright) returning null

### ISSUE THREAD

**Issue by Jicksin** [Hupotronic/ExLinks#56]
The navbotright node is now cloned from navtopright, so it cannot be found during execution. A quick fix is commenting out 
```
$.prepend($.id('navbotright'),$.elem(arrbot));
```
The bottom exlinks settings button still doesn't work.

**Comment by Daiz** [comment]
"Fixed" with a temporary patch to make sure ExLinks works, though it doesn't fix the bottom menu button not working issue. But anyway, this shall do for now.
